export const GET_DATA = 'experiences/GET_DATA';
export const GET_DATA_SUCCESS = 'experiences/GET_DATA_SUCCESS';
export const GET_DATA_FAILURE = 'experiences/GET_DATA_FAILURE';

export const GET_EXPERIENCE_DETAIL = 'experiences/GET_EXPERIENCE_DETAIL';
export const GET_EXPERIENCE_DETAIL_SUCCESS = 'experiences/GET_EXPERIENCE_DETAIL_SUCCESS';
export const GET_EXPERIENCE_DETAIL_FAILURE = 'experiences/GET_EXPERIENCE_DETAIL_FAILURE';

export const GET_SUBCATEGORY_EXPERIENCES = 'experiences/GET_SUBCATEGORY_EXPERIENCES';
export const GET_SUBCATEGORY_EXPERIENCES_SUCCESS = 'experiences/GET_SUBCATEGORY_EXPERIENCES_SUCCESS';
export const GET_SUBCATEGORY_EXPERIENCES_FAILURE = 'experiences/GET_SUBCATEGORY_EXPERIENCES_FAILURE';
