export const GET_FEATURED_EXPERIENCES = 'GET_FEATURED_EXPERIENCES';
export const GET_FEATURED_EXPERIENCES_SUCCESS = 'GET_FEATURED_EXPERIENCES_SUCCESS';
export const GET_FEATURED_EXPERIENCES_FAILURE = 'GET_FEATURED_EXPERIENCES_FAILURE';

export const GET_LOCATIONS = 'GET_LOCATIONS';
export const GET_LOCATIONS_SUCCESS = 'GET_LOCATIONS_SUCCESS';
export const GET_LOCATIONS_FAILURE = 'GET_LOCATIONS_FAILURE';
export const SET_SELECTED_LOCATION = 'SET_SELECTED_LOCATION';
