export const TOGGLE_MENU = 'TOGGLE_MENU';
export const SET_SEARCH_QUERY = 'SET_SEARCH_QUERY';

export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const GET_CATEGORIES_FAILURE = 'GET_CATEGORIES_FAILURE';
